### ISSUE TITLE
No Stats on CoreOS

### ISSUE THREAD

**Issue by ashmere** [docker-infra/container_exporter#4] opened 2015-03-16 17:37 UTC
no stats are collected on coreos
started as 
{code}
docker run -d  --name container_exporter -p 9104:9104 -v /sys/fs/cgroup:/cgroup -v /var/run/docker.sock:/var/run/docker.sock prom/container-exporter:latest
{code}

example 
{code}
# TYPE container_cpu_usage_seconds_total counter

container_cpu_usage_seconds_total{id="76ad37b466443f963486695e8c7270c56d62d2238513567b3e6cf927311e36d8",image="prom/container-exporter:latest",name="container_exporter",type="kernel"} 0
container_cpu_usage_seconds_total{id="76ad37b466443f963486695e8c7270c56d62d2238513567b3e6cf927311e36d8",image="prom/container-exporter:latest",name="container_exporter",type="user"} 0
{code}

I suspect this is having issue with the cgroups are rearranged on coreos 
example of cgroup on most systems
{code}
/sys/fs/cgroup/docker/%(id)/cgroup.procs
{code}
in coreos
{code}
/sys/fs/cgroup/systemd/system.slice/docker-%(id).scope/cgroup.procs
{code}

**Comment by discordianfish** [comment] 2015-05-07 10:54
Duplicate of #1

**Closed as completed by discordianfish** 2015-05-07 10:54 UTC
